### ISSUE TITLE
Store images as webp, use Git LFS, or consider rewriting history over time.

### ISSUE THREAD

**Issue by MatthewCroughan** [gytis-ivaskevicius/high-quality-nix-content#4]
Since we're storing binary information, we should either use Git LFS (Maybe even pin using IPFS). Although, if we insist on keeping this simple and having a git repository here, there are two immediate things we can do to improve the situation:

- Store images as `webp` format (`magick wizard.png -quality 50 -define webp:lossless=true wizard.webp`)
- Squash/Rewrite the history at some filesize threshold like 50MB.

The history of commits on this repository are not useful, since we have `creators.nix` which gives credits, commits are not needed.

**Comment by gytis-ivaskevicius** [comment]
Git LFS/IPFS does not bring any value for this particular case since images are added and never changed thus there is no Git overhead.

As for image format - I am down for changing it but unfortunately, not everything accepts `webp` file format which will likely become an inconvenience for lots of peeps. So basically here is file format requirements:
- Highest possible quality (no lossy compression or anything)
- File format must be widely acceptable which leaves us with `png`, `jpg`, `gif`, ~~`bmp`~~

**Comment by MatthewCroughan** [comment]
@gytis-ivaskevicius Why should we care about what Internet Explorer 7 supports? The fact of the matter is that most browsers support webp, apng, etc. These are new technologies, so we shouldn't be afraid to use them and proliferate their usage, especially in a repository like this which is designed for fun.

**Comment by gytis-ivaskevicius** [comment]
There are cases where you are not able to upload webp, so if a user wishes to use it as let's say profile picture it may cause problems.
Also, I like the idea of using images of original quality even though it's likely that nobody would notice the difference. Feel free to implement some auto-conversion mechanism, I am not against it
